### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by babbahotep** [KurtSanders/STBitBarApp-V2#1]
repo does show up in ST IDE

**Comment by KurtSanders** [comment]
The project is active.  There has not been any need for bug fixes or enhancements in quite sometime!  

I just checked my ST repo list and it is showing up.  Please verify that you have this exact entry for your repo.

![image](https://user-images.githubusercontent.com/12133562/58405159-d4e5de80-8034-11e9-8811-84328831568c.png)
