### ISSUE TITLE
Exit status 99

### ISSUE THREAD

**Issue by beaglecodes** [KurtSanders/STBitBarApp-V2#3]
I'm trying to google these issues but not getting any hits...but I haven't been able to get this working on two different Macs running Big Sur. 

I'm trying to install the SmartThings bitbar (xbar) plugin. I followed all the instructions including `chmod`ing the script, the entire folder, etc. The xbar menu icon has a yellow triangle with exclamation in the middle. When I click on the xbar icon, it says `fork/exec ./ST: permission denied` and also `Make your script executable: chmod +x ST`. I've tried chmoding and sudo chmoding many times now.

When I open the Plugin Browser, it says at the top in a yellow banner `Something went wrong, this: Get "https://xbarapp.com/docs/plugins/categories.json": context deadline exceeded`

The St.1m.sh menu bar item says `exit status 99`.

Any tips on what to try?

<img width="158" alt="Screen Shot 2021-03-15 at 10 23 29 PM" src="https://user-images.githubusercontent.com/22315097/111259925-26ca7080-85dd-11eb-81fc-eae51d9c840c.png">

**Comment by KurtSanders** [comment]
I am no longer using SmartThings.   This ST app is no longer supported.
